### ISSUE TITLE
[Feature Request] Resizable device preview

### ISSUE THREAD

**Issue by Martinocom** [software-mansion/radon-ide#201]
Hello there! I started using this plugin and I'm starting to love it. 

One thing that bothers me is that usually I'm used to keep only a small simulator compared to my "dev" window, since I need only a quick preview. With RN-IDE the window won't resize if scaled horizontally (but somehow manages to scale vertically) and seems very big to me. It would be great to have the possibility to scale it accordingly to the container.

Proof of concept: https://youtu.be/4w5me-MX5uo

Comparing two sizes of simulators and "consumed" space.

<img src="https://github.com/software-mansion/react-native-ide/assets/17514549/7d26493e-956d-40b3-bece-9de6e6c552ac" width="270" />
<img src="https://github.com/software-mansion/react-native-ide/assets/17514549/c64d37d8-b182-47d1-bc03-19e8b53b1118" width="270" />

I digged into the code and I found some minimal steps to achieve a desirable solution, even if not production ready. It will disable the device frame, the mask and will break menus, but the simulator will be usable. with a smaller dimension.

```css
.phone-wrapper {
    display: flex;
    justify-content: center;
    /* overflow: auto; */
    width: 100%;
    height: 100%;
    aspect-ratio: var(--phone-aspect-ratio);
    /* position: relative; */
    /* -webkit-user-select: none; */
    /* user-select: none;
}

.phone-content {
    /* position: relative; */
    display: flex;
    flex: 1;
    /* min-height: var(--min-height); */
    aspect-ratio: var(--phone-aspect-ratio);
}

.phone-screen {
    /* position: absolute; */
    /* width: calc(100% - 14px); */
    /* height: 100%; */
    /* top: 0; */
    /* left: 7px; */
    /* -webkit-mask-image: var(--phone-mask-image); */
    /* mask-image: var(--phone-mask-image); */
    /* -webkit-mask-size: cover; */
    /* mask-size: cover; */
}

 /* + removed the image of the frame */
```

Proof of concept: https://youtu.be/WKTnZOWVG0s

Since there are breaking changes and I tested it only with Android Simulator, I'm not ready to post a PR yet, but I wanted to post my discoveries with others, also to keep track of the progress of this particular feature.

Happy coding!
